### ISSUE TITLE
Request for project overview

### ISSUE THREAD

**Issue by Ask149** [Daniel061/Baby6.1#23]
Hi, I was able to study and understand most of the essential portion of the codebase, but I am still facing difficulty in understanding the exact flow and working of the project.

It would be really great if you could provide a short description of the project and a use-case which will cover at least some of its execution aspects.

**Comment by Daniel061** [comment]
Hi,
Please take a look at Wiki page [Program Flow](https://github.com/Daniel061/Baby6.1/wiki/Program-Flow) to see if that answers any of your questions.

I'll be glad to answer anything you may still have questions with.

> It would be really great if you could provide a short description of the project and a use-case which will cover at least some of its execution aspects.

A very short description of the project is to develop a natural English understanding program and use this to drive AI. Once the program is fully taught how to learn, the program's implementation of this knowledge is the next step.

Also, if you are able to execute the program, type the command verbose[enter]  and then a simple sentence. Most routines will report when they are in use and how they contributed.

I hope this helps.

Daniel

**Comment by Daniel061** [comment]
How are you doing with the program flow understanding? 

Did you see my proposal for Tokenizer() change?

I wish there was a message feature inside this project.

Daniel

**Comment by Daniel061** [comment]
I spent some time writing an expanded program flow explanation . Take a look at it if you have the time.

[Program flow expanded.](https://github.com/Daniel061/Baby6.1/wiki/Program-Flow-(Expanded))

Daniel
