### ISSUE TITLE
What is the Cat's Name?

### ISSUE THREAD

**Issue by mackenzieankrom** [Daniel061/Baby6.1#33]
When asked what the cat's name is, she doesn't know, even though she has been told it's name.

**To Reproduce**
1. Tell her "The cat is black"
2. Answer "yes" to her question about "A black cat?"
3. Tell her "Precious is a cat"
4. Answer "yes" when she asks if Precious is the cat's name.
5. Ask her "What is the cat's name?"
6. Error, she doesn't know the cat's name. 

 - Version: Baby 6

**Comment by Daniel061** [comment]
Added contraction work to deal with ownership and some two word break outs, i.e. what's to what is.
Added logic in question handler to deal with a name request as well as a gender request.
Added logic to query the user about the gender of a proper noun.
